apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://ecommerce-registry:8761/eureka/"
  SPRING_REDIS_HOST: "redis"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_ELASTICSEARCH_URIS: "http://elasticsearch:9200"
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  JWT_SECRET: "ecommerce-secret-key-that-is-at-least-32-chars-long-12345"
  MINIO_ROOT_PASSWORD: "minioadmin"
